// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uydbxttvxoxwdyhgbxvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5ZGJ4dHR2eG94d2R5aGdieHZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MTE3NDAsImV4cCI6MjA3MjA4Nzc0MH0.IPohxPy6GN5w8OFUh96dwH0wjt4vSoAo36Yf4xD5nzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});